config/routes.rb
WishList::Application.routes.draw do

  get "pages/admin"
  get "pages/draw_rules"
  get "pages/ownerships"

  resources :users do
    member do
      get :draw_excluding
      get :ownerships
    end
  end
  resources :wish_items, :only => [:create, :destroy, :edit, :update, :index, :show]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :draw_names, :only => [:new, :create, :index]
  resources :draw_exclusions, :only => [:create, :destroy]
  resources :ownerships, :only => [:create, :destroy]
  resources :draw_name_history, :only => [:create]
  
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

  get "sessions/switch"
  
  get "wish_items/feed"
  match '/feed' => 'wish_items#feed', :as => :feed, :defaults => { :format => 'atom' }

  post "draw_names/clear"
  
  get 'draw_name_history/view'
  
  root :to => 'wish_items#index'
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean         default(FALSE)
#  created_at         :datetime
#  updated_at         :datetime
#

require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password, :accessible
  attr_accessible :name, :email, :password, :password_confirmation

  has_many :wish_items, :dependent => :destroy
  has_one :drawn_name, :foreign_key => "giver_id", :dependent => :destroy
  has_many :drawn_name_histories, :foreign_key => "giver_id", :dependent => :destroy
  has_many :draw_exclusions, :foreign_key => "excluder_id", :dependent => :destroy
  has_many :draw_excluding, :through => :draw_exclusions, :source => :excluded
  has_many :ownerships, :foreign_key => "owner_id", :dependent => :destroy
  has_many :owned, :through => :ownerships, :source => :owned

  default_scope :order => 'users.name ASC'
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
                   :length => { :maximum => 50 }
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 12..40 }

  before_validation :update_password
  before_save :encrypt_password

  # Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def is_admin=(v)
    self.admin = v
  end
  
  def is_admin
    self.admin
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  # does the user exclude a specified user from being drawn?
  def draw_excluding?(excluded)
    draw_exclusions.find_by_excluded_id(excluded)
  end

  # exclude a specified user from being drawn
  def draw_exclude!(excluded)
    draw_exclusions.create!(:excluded_id => excluded.id)
  end
  
  # include a specified user so that the name can be drawn
  def draw_include!(excluded)
    draw_exclusions.find_by_excluded_id(excluded).destroy
  end
  
  # does the user own the specified user
  def owns?(owned)
    ownerships.find_by_owned_id(owned)
  end

  def own!(owned)
    ownerships.create!(:owned_id => owned.id)
  end

  def unown!(owned)
    ownerships.find_by_owned_id(owned).destroy
  end
  
  # get all users that can be excluded (i.e., all users in the draw other than the 
  # current user and already excluded users)
  def self.draw_excludable(user)
    clause = "in_draw = 't' and id <> ?"
    if user.draw_exclusions.count > 0
      clause += " and id not in (#{user.draw_exclusions.map(&:excluded_id).join(",")})"
    end
    where(clause, user)
  end

  # get all users that can be owned (i.e., all users other than the 
  # current user and already owned users)
  def self.ownable(user)
    clause = "admin = 'f' and id <> ?"
    if user.ownerships.count > 0
      clause += " and id not in (#{user.ownerships.map(&:owned_id).join(",")})"
    end
    where(clause, user)
  end

  private
  
    def encrypt_password
      if encrypted_password.blank? || password != encrypted_password[0..39]
        self.salt = make_salt if new_record?
        self.encrypted_password = encrypt(password)
      end
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
    
    def mass_assignment_authorizer
      super + (accessible || [])
    end
    
    def update_password
      if password.blank? && !encrypted_password.blank?
        self.password = encrypted_password[0..39]
        if password_confirmation.blank?
          self.password_confirmation = password
        end
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :except => [:show, :index]
  before_filter :correct_user, :only => [:edit, :update, :draw_excluding]
  before_filter :admin_user, :only => [:new, :create, :ownerships]

  def new
    @user = User.new
    @title = "Add User"
  end
  
  def create
    @user = User.new
    @user.accessible = [:admin, :in_draw] if current_user.admin?
    @user.update_attributes(params[:user])
    if @user.save
      flash[:success] = "Added user #{@user.name}"
      redirect_to users_path
    else
      @title = "Add User"
      @user.password = ""
      @user.password_confirmation = ""
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @wish_items = @user.wish_items
    @wish_item = WishItem.new
    @categories = WishCategory.all
    @title = @user.name
    store_location
  end
  
  def edit
    @title = "Edit Account"
  end
  
  def update
    unless current_user.has_password?(params[:old_password]) || current_user.admin?
      flash.now[:error] = "Current password entered does not match your actual password."
      @title = "Edit Account"
      return render 'edit'
    end
    @user.accessible = [:admin, :in_draw] if current_user.admin?
    if @user.update_attributes(params[:user])
      flash[:success] = "Account updated."
      redirect_to @user
    else
      @title = "Edit Account"
      render 'edit'
    end
  end
  
  def index
    @users = User.all
    @title = "Wishers"
  end
  
  def draw_excluding
    @title = "Exclusions"
    @user = User.find(params[:id])
    if current_user.admin?
      @users = User.draw_excludable(@user)
    end
  end
  
  def ownerships
    @title = "Ownerships"
    @user = User.find(params[:id])
    if current_user.admin?
      @users = User.ownable(@user)
    end
  end
  
  private
  
    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user) || current_user.admin?
        flash[:error] = "You are not an owner of #{request.fullpath}."
        redirect_to(root_path)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    options.merge!( { :secure => request.ssl? } )
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<% if current_user.admin? %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
<% else %>
  <h3><%= @user.name %></h3>
<% end %>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<% unless current_user.admin? %>
  <div class="field">
    <%= label_tag :old_password, "Current password" %><br />
    <%= password_field_tag :old_password, nil, :size => 30 %>
  </div>
<% end %>
<div class="field">
  <%= f.label :password, "New password" %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "New password confirmation" %><br />
  <%= f.password_field :password_confirmation %>
</div>
<% if current_user.admin? %>
  <div class="field">
    <%= f.check_box :admin %><%= f.label :admin %>
  </div>
  <div class="field">
    <%= f.check_box :in_draw %><%= f.label :in_draw, "In the Christmas draw" %>
  </div>
<% end %>

app/views/users/draw_excluding.html.erb
<h1>Exclusions</h1>

<% if @user.in_draw %>
  <% if @user.draw_excluding.count > 0 %>
    <p><%= relative_user_name(@user) %> cannot draw the following names:</p>
    <ul class="users">
      <% @user.draw_excluding.each do |excluded| %>
        <li>
          <% unless current_user.admin? %>
            <%= gravatar_for excluded, :size => 30 %>
            <%= link_to excluded.name, excluded %>
          <% else %>
            <%= form_for @user.draw_exclusions.find_by_excluded_id(excluded),
                         :html => { :method => :delete } do |f| %>
              <%= f.hidden_field :excluded_id %>
              <%= f.hidden_field :excluder_id %>
              <%= gravatar_for excluded, :size => 30 %>
              <%= link_to excluded.name, excluded %>
              <%= f.submit "Can draw" %>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
    <p>If someone needs to be added or removed from this list, contact <%= webmaster_contact %>.</p>
  <% else %>
    <p><%= relative_user_name(@user) %> can draw anyone's name. To add a name that you cannot draw, contact <%= webmaster_contact %>.</p>
  <% end %>
<% else %>
  <p><%= relative_user_name(@user) %> are not in the Christmas draw. To be added to the draw, contact <%= webmaster_contact %>.</p>
<% end %>

<% if current_user.admin? %>
  <ul class="users">
    <% @users.each do |user| %>
      <li>
        <%= form_for @user.draw_exclusions. 
                          build(:excluded_id => user.id) do |f| %>
          <%= f.hidden_field :excluded_id %>
          <%= f.hidden_field :excluder_id %>
          <%= gravatar_for user, :size => 30 %>
          <%= link_to user.name, user %> - 
          <%= f.submit "Cannot draw" %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<p>See <%= link_to "all exclusions", pages_draw_rules_path %>.</p>

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= form_for(@user) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>All Wishers</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, :size => 30 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Add a user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.check_box :admin %><%= f.label :admin %>
  </div>
  <div class="actions">
    <%= f.submit "Add User" %>
  </div>
<% end %>

app/views/users/ownerships.html.erb
<h1>Ownerships</h1>

<% if @user.owned.count > 0 %>
  <p><%= relative_user_name(@user) %> owns the following accounts:</p>
  <ul class="users">
    <% @user.owned.each do |owned| %>
      <li>
        <% unless current_user.admin? %>
          <%= link_to owned.name, owned %>
        <% else %>
          <%= form_for @user.ownerships.find_by_owned_id(owned),
                       :html => { :method => :delete } do |f| %>
            <%= f.hidden_field :owned_id %>
            <%= f.hidden_field :owner_id %>
            <%= link_to owned.name, owned %>
            <%= f.submit "Unown" %>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <p>If someone needs to be added or removed from this list, contact <%= webmaster_contact %>.</p>
<% else %>
  <p><%= relative_user_name(@user) %> owns no accounts. To own an account, contact <%= webmaster_contact %>.</p>
<% end %>

<% if current_user.admin? %>
  <ul class="users">
    <% @users.each do |user| %>
      <li>
        <%= form_for @user.ownerships. 
                          build(:owned_id => user.id) do |f| %>
          <%= f.hidden_field :owned_id %>
          <%= f.hidden_field :owner_id %>
          <%= link_to user.name, user %> - 
          <%= f.submit "Own" %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<p>See <%= link_to "all ownerships", pages_ownerships_path %>.</p>

app/views/users/show.html.erb
<h1><%= gravatar_for @user %><%= @user.name %></h1>

<% if current_user?(@user) %>
  <div>
    <p><a href="http://gravatar.com/emails" target="_blank">Change image (gravatar)</a></p>
  </div>
  <% if @user.admin? %>
    <p>Administrator</p>
  <% end %>
  <% if @user.in_draw? %>
    <p>You are in the Christmas draw.
    <% unless @user.drawn_name.blank? %>
      You drew <%= link_to @user.drawn_name.receiver.name, @user.drawn_name.receiver %>.
    <% else %>
      No name has been drawn for you yet.
    <% end %>
      See <%= link_to "who you cannot draw", :draw_excluding_user %>.
    </p>
  <% end %>
  <p>See <%= link_to "past Christmas draws", draw_name_history_view_path %>.</p>
  <table class="front">
    <tr>
      <td>
        <h3 class="wish_item">Add a wish to your wish list:</h3>
        <%= render 'wish_items/wish_item_form' %>
      </td>
    </tr>
  </table>
<% end %>
<% unless @user.wish_items.empty? %>
  <table class="front">
    <tr>
      <td class="wish_lists">
        <h3>Wish List</h3>
        <ul class="wish_items">
          <%= render @wish_items %>
        </ul>
      </td>
    </tr>
  </table>
<% end %>