config/routes.rb
WishList::Application.routes.draw do

  get "pages/admin"
  get "pages/draw_rules"
  get "pages/ownerships"

  resources :users do
    member do
      get :draw_excluding
      get :ownerships
    end
  end
  resources :wish_items, :only => [:create, :destroy, :edit, :update, :index, :show]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :draw_names, :only => [:new, :create, :index]
  resources :draw_exclusions, :only => [:create, :destroy]
  resources :ownerships, :only => [:create, :destroy]
  resources :draw_name_history, :only => [:create]
  
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

  get "sessions/switch"
  
  get "wish_items/feed"
  match '/feed' => 'wish_items#feed', :as => :feed, :defaults => { :format => 'atom' }

  post "draw_names/clear"
  
  get 'draw_name_history/view'
  
  root :to => 'wish_items#index'
  

end

app/models/wish_item.rb
# == Schema Information
#
# Table name: wish_items
#
#  id          :integer         not null, primary key
#  description :text
#  url         :string(255)
#  category_id :integer
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class WishItem < ActiveRecord::Base
  attr_accessible :description, :url, :category_id, :user_id

  belongs_to :user
  belongs_to :category, :class_name => "WishCategory", :foreign_key => "category_id"
  
  default_scope :order => 'wish_items.created_at DESC'

  url_regex = /\A\z|\Ahttps?:\/\/[^<^>^"^']+\z/i
  
  validates :description, :presence => true,
                          :length => { :maximum => 4000 }
  validates :url, :length => { :maximum => 2000 }, 
                  :format => { :with => url_regex }
  validates :category_id, :presence => true
  validates :user_id, :presence => true
end

app/controllers/wish_items_controller.rb
class WishItemsController < ApplicationController
  before_filter :authenticate, :except => [:show, :index, :feed]
  before_filter :authorized_user, :only => [:edit, :update, :destroy]

  def create
    params[:wish_item][:url] = nice_url(params[:wish_item][:url])
    @wish_item = current_user.wish_items.build(params[:wish_item])
    @wish_item.description.gsub!(/\n/, "<br/>")
    if WishCategory.count == 0
      WishCategory.create(:name => "none")
    end
    category = WishCategory.first
    @wish_item.category_id = category.id
    if @wish_item.save
      flash[:success] = "Added wish"
      respond_to do |format|
        format.html { redirect_back_or root_path @user }
        format.js
      end
    else
      get_users
      respond_to do |format|
        format.html { render 'wish_items/bare_wish_item_form' }
        format.js
      end
    end
  end

  def destroy
    @wish_item.destroy
    redirect_back_or root_path
  end
  
  def index
    get_users
    if logged_in?
      @wish_item = WishItem.new
      store_location
    end
  end

  def feed
    @title = "Wish Lists"
    @wish_items = WishItem.order("updated_at desc")
    @updated = @wish_items.first.updated_at unless @wish_items.empty?
    
    respond_to do |format|
      format.atom { render :layout => false }
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end
  end
  
  def show
    redirect_to wish_items_path(:anchor => "wish" + params[:id])
  end
  
  def edit
    @title = "Edit Wish"
    @wish_item = WishItem.find(params[:id])
    @wish_item.description.gsub!(/<br\/>/, "\n")
  end
  
  def update
    params[:wish_item][:url] = nice_url(params[:wish_item][:url])
    params[:wish_item][:description].gsub!(/\n/, "<br/>")
    if @wish_item.update_attributes(params[:wish_item])
      flash[:success] = "Updated wish."
      redirect_back_or root_path
    else
      @title = "Edit Wish"
      @wish_item.description.gsub!(/<br\/>/, "\n")
      render 'edit'
    end
  end
  
  private
  
    def get_users
      @users = User.all
      if logged_in?
        current_user_index = @users.index { |i| i.id == current_user.id }
        @users.unshift(@users.slice!(current_user_index))
      end
    end
    
    def authorized_user
      @wish_item = current_user.wish_items.find_by_id(params[:id])
      redirect_to root_path if @wish_item.nil?
    end
    
    def nice_url(url)
      return url if url.blank? or url.downcase.starts_with?("http")
      "http://" + url
    end
end

app/helpers/wish_items_helper.rb
module WishItemsHelper

  def make_wish(wish)
    # wish_text = ""
    # unless wish.category.none?
      # wish_text = wish.category.name + ": "
    # end
    # wish_text += wish.description
    wish_text = wish.description
    
    if wish.url.blank?
      wrap(wish_text)
    else
      link_to(wrap(wish_text), wish.url)
    end
  end

  def make_fake_wish
    fake_wish = 
      [ { :description => "Rubber bits", 
          :url => ""
        },
        { :description => "Everything by John Milton",
          :url => "http://www.amazon.com/Complete-Poetry-Essential-Milton-Library/dp/0679642536"
        },
        { :description => "Beano tablets",
          :url => "http://www.amazon.com/Dietary-Supplement-Tablets-100-Count-Bottles/dp/B000FKJX2G"
        },
        { :description => "First season of Mama's Family",
          :url => "http://www.amazon.com/Mamas-Family-Complete-First-Season/dp/B000GH3PMM"
        },
        { :description => "World peace",
          :url => "http://zombo.com/"
        },
        { :description => "Everything by Tolstoy",
          :url => "http://www.amazon.com/Tolstoy-Karenina-Resurrection-Confession-ebook/dp/B000WT51FS"
        },
        { :description => "Socks",
          :url => "http://www.amazon.com/FULL-TILT-Cupcake-Pack-Socks/dp/B00594VC22"
        },
        { :description => "A Zune",
          :url => "http://www.amazon.com/Zune-Video-MP3-Player-Black/dp/B002JPITXY"
        },
        { :description => "Race car bed",
          :url => "http://www.amazon.com/Little-Tikes-Lightning-McQueen-Race/dp/B000FECQOY"
        },
        { :description => "Head wipes",
          :url => "http://www.baldguyz.com/headwipes"
        },
        { :description => "Pocket chair",
          :url => "https://www.pocketchair.com/"
        },
        { :description => "Tongue scraper",
          :url => "http://laughingsquid.com/his-and-her-tongue-scrapers/"
        },
        { :description => "A mogwai",
          :url => "http://www.youtube.com/watch?v=zoK0BzYUTrU"
        },
        { :description => "Red Ryder BB gun",
          :url => "http://www.youtube.com/watch?v=ppOXpyhM2wA"
        },
        { :description => "A cashmere sweater",
          :url => "http://www.youtube.com/watch?v=dTsTFTIvwJw"
        },
        { :description => "Okama Gamesphere",
          :url => ""
        },
        { :description => "An IBC towel",
          :url => "http://www.imdb.com/title/tt0096061/quotes?qt0266442"
        },
        { :description => "USB Toaster",
          :url => "http://store.theonion.com/product/usb-powered-toastergift-box,29/"
        },
        { :description => "Potty putter",
          :url => "http://www.youtube.com/watch?v=Cp5FAbJvUEY"
        },
        { :description => "Spam",
          :url => "http://www.spam.com/"
        }
      ].sample
    
    if fake_wish[:url].blank?
      wrap(fake_wish[:description])
    else
      link_to(wrap(fake_wish[:description]), fake_wish[:url])
    end
  end
  
  def wrap(content)
    tags = %w(a b strong em br sub sup)
    if content =~ /<(\S)+.*?>.*<\/\1>/
      # todo: wrap only the visible content (e.g., not invisible hrefs)
      text = content
    else
      text = content.split.map{ |s| wrap_long_string(s) }.join(' ')
    end
    sanitize(raw(text), :tags => tags, :attributes => %w(href))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : 
                                  text.scan(regex).join(zero_width_space)
    end
end

app/views/wish_items/_wish_item.html.erb
<li id="wish<%= wish_item.id %>">
  <span class="description">
    <%= make_wish(wish_item) %>
  </span>
  <% if current_user?(wish_item.user) %>
    -
    <%= link_to "edit", edit_wish_item_path(wish_item) %> |
    <%= link_to "delete", wish_item, :method => :delete,
                                     :confirm => "Are you sure you want to delete the wish?",
                                     :title => wish_item.description %> 
  <% end %>
</li>

app/views/wish_items/_wish_item_form.html.erb
<%= form_for @wish_item do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <table>
    <tr>
      <td>Wish <%= "#" + (current_user.wish_items.count + 1).to_s if @wish_item.id.blank? %><br/>Description</td>
      <td>
        <div class="field">
          <%= f.text_area :description %>
        </div>
      </td>
    </tr>
    <tr>
      <td>Link</td>
      <td>
        <div class="field">
          <%= f.text_field :url %>
        </div>
      </td>
    </tr>
  </table
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/wish_items/bare_wish_item_form.html.erb
<table class="front">
  <% if logged_in? %>
    <tr>
      <td>
        <h3 class="wish_item">Add an item to your wish list:</h3>
        <%= render 'wish_item_form' %>
      </td>
    </tr>
  <% end %>
</table>

app/views/wish_items/edit.html.erb
<table class="front">
  <tr>
    <td>
      <h1 class="wish_item">Edit Wish</h1>
      <%= render 'wish_item_form' %>
    </td>
  </tr>
</table>

app/views/wish_items/index.html.erb
<table class="front">
  <% if logged_in? %>
    <tr>
      <td>
        <h1 class="wish_item">What do you want?</h1>
        <%= render 'wish_item_form' %>
      </td>
    </tr>
    <% unless current_user.drawn_name.blank? %>
      <tr>
        <td>
          You drew <%= link_to current_user.drawn_name.receiver.name, current_user.drawn_name.receiver %> in the Christmas draw.<br/><br/>
        </td>
      </tr>
    <% end %>
  <% end %>
  <tr>
    <td class="wish_lists">
    <h1>Wish Lists</h1>
    <% @users.each do |user| %>
      <h2><%= gravatar_for user, :size => 30 %> <%= link_to user.name, user %></h2>
      <ul class="wish_items">
        <% if user.wish_items.count > 0 %>
          <%= render user.wish_items %>
        <% else %>
          <li><%= make_fake_wish %></li>
        <% end %>
      </ul>
    <% end %>
    </td>
  </tr>
</table>