config/routes.rb
WishList::Application.routes.draw do

  get "pages/admin"
  get "pages/draw_rules"
  get "pages/ownerships"

  resources :users do
    member do
      get :draw_excluding
      get :ownerships
    end
  end
  resources :wish_items, :only => [:create, :destroy, :edit, :update, :index, :show]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :draw_names, :only => [:new, :create, :index]
  resources :draw_exclusions, :only => [:create, :destroy]
  resources :ownerships, :only => [:create, :destroy]
  resources :draw_name_history, :only => [:create]
  
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

  get "sessions/switch"
  
  get "wish_items/feed"
  match '/feed' => 'wish_items#feed', :as => :feed, :defaults => { :format => 'atom' }

  post "draw_names/clear"
  
  get 'draw_name_history/view'
  
  root :to => 'wish_items#index'
  

end

app/views/pages/admin.html.erb
<h1>Administration</h1>

<%= link_to "Add a user", new_user_path %><br/>
<%= link_to "See users", users_path %></br>
<%= link_to "See user ownerships", pages_ownerships_path %><br/>
<%= link_to "See drawing rules", pages_draw_rules_path %><br/>
<%= link_to "Draw names", new_draw_name_path %><br/>
<%= link_to "See drawn names", draw_names_path %>

app/views/pages/draw_rules.html.erb
<h1>Draw Rules</h1>

<h3>People in the draw</h3>
<ul class="users">
  <% @givers.each do |user| %>
    <li>
      <%= gravatar_for user, :size => 30 %>
      <%= link_to user.name, draw_excluding_user_path(user) %>
      <% if user.draw_excluding.count > 0 %>
        cannot draw the following names:
        <ul>
          <% user.draw_excluding.each do |excluded| %>
            <li>
              <%= gravatar_for excluded, :size => 30 %>
              <%= link_to excluded.name, excluded %>
            </li>
          <% end %>
        </ul>
      <% else %>
        can draw any name
      <% end %>
    </li>
  <% end %>
</ul>

<h3>People not in the draw</h3>
<ul>
  <% @drawless.each do |user| %>
    <li>
      <%= gravatar_for user, :size => 30 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/pages/ownerships.html.erb
<h1>User Ownerships</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, ownerships_user_path(user) %>
      <% if user.owned.count > 0 %>
        owns the following users:
        <ul>
          <% user.owned.each do |owned| %>
            <li>
              <%= link_to owned.name, owned %>
            </li>
          <% end %>
        </ul>
      <% else %>
        owns no one
      <% end %>
    </li>
  <% end %>
</ul>