config/routes.rb
WishList::Application.routes.draw do

  get "pages/admin"
  get "pages/draw_rules"
  get "pages/ownerships"

  resources :users do
    member do
      get :draw_excluding
      get :ownerships
    end
  end
  resources :wish_items, :only => [:create, :destroy, :edit, :update, :index, :show]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :draw_names, :only => [:new, :create, :index]
  resources :draw_exclusions, :only => [:create, :destroy]
  resources :ownerships, :only => [:create, :destroy]
  resources :draw_name_history, :only => [:create]
  
  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy'

  get "sessions/switch"
  
  get "wish_items/feed"
  match '/feed' => 'wish_items#feed', :as => :feed, :defaults => { :format => 'atom' }

  post "draw_names/clear"
  
  get 'draw_name_history/view'
  
  root :to => 'wish_items#index'
  

end

app/views/layouts/_header.html.erb
<header>
  <% if logged_in? %>
    <nav class="round" id="left">
      <ul>
        <li>Hello <%= link_to current_user.name, current_user %></li>
      </ul>
    </nav>
  <% end %>
  <nav class="round" id="right">
    <ul>
      <% if !current_page?(root_path) %>
        <li><%= link_to "Wish Lists", root_path %></li>
      <% end %>
      <% if logged_in? %>
        <% if current_user.admin? %>
          <li><%= link_to "Admin", pages_admin_path %></li>
        <% end %>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Account", edit_user_path(current_user) %></li>
        <% if current_user.owned.count > 0 %>
          <li>Log in as <%= raw(get_owned_links(current_user.owned)) %></li>
        <% end %>
        <li><%= link_to "Log Out", logout_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Log In", login_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= auto_discovery_link_tag :atom, root_path + "feed.atom" %>
    <%= auto_discovery_link_tag :rss, root_path + "feed.rss" %>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>